### ISSUE TITLE
date: invalid date ‘@null’

### ISSUE THREAD

**Issue by PhilT001** [hakerdefo/pmwf#1]
hi, i'm getting the following on two different systems, one is a 64 bit debian stretch install and the other is an embedded arm device with a 'debian like' o/s

date: invalid date ‘@null’
date: invalid date ‘@null’
date: invalid date ‘@null’
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null

**Comment by hakerdefo** [comment]
Hi there PhilT001,
Add following two lines at the top (right below "#!/bin/bash" line) of the file 'pmwf',

`export LC_TIME=C`
`export LC_ALL=C`

After adding these two lines, beginning of the file should look like this,

`#!/bin/bash`
`export LC_TIME=C`
`export LC_ALL=C`

Save the file and run the script again.
Cheers!!!

**Comment by PhilT001** [comment]
Hi, that got it working!

Many thanks,

Phil.

**Comment by hakerdefo** [comment]
Updated the script with afore mentioned fix.
